#!/usr/bin/env bash

## Description: Run a symfony console command
## Usage: console [command] [...args]
## Example: ddev console framework:demodata -p 10 --reset-defaults

if [[ ! -f "bin/console" ]]; then
    echo "console runner does not exist."

    exit 1;
fi
while getopts "e:" param; do
    while read arg; do
        export "$arg"
    done <<< "$(echo $OPTARG | xargs -d ',' -n 1)"
    shift 2
done

bin/console "$@"
